services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: vue-app-dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '8003:1818'
    environment:
      - CHOKIDAR_USEPOLLING=true # Enables hot-reloading with volumes
    command: npm run dev
